/**
 * sw.js (Service worker): full offline support with an explicit, user-visible update flow.
 *
 * - install:  precache every file listed in precache-manifest.js (generated by tools/precache.mjs).
 *             Delta update: a file whose content hash is unchanged is copied from the previous
 *             version's cache; only new or changed files are downloaded, each checked against its
 *             hash (see fetchVerified). Posts { type: 'precache-progress', done, total, downloaded }
 *             to open pages for the progress UI.
 * - activate: delete caches from older versions.
 * - fetch:    same-origin GETs are served cache-first (navigations fall back to index.html);
 *             cross-origin requests (GitHub firmware downloads, update manifests) go straight to the
 *             network and are never cached, so firmware checks are always fresh.
 * - message:  'skip-waiting' lets the page apply a waiting update when the user taps Restart.
 */
importScripts('precache-manifest.js');

const { version, files, hashes = {} } = self.__PRECACHE;
const CACHE = `hhl-config-${version}`;
const PREFIX = 'hhl-config-';
const CONCURRENCY = 6;

async function broadcast(msg) {
  const clients = await self.clients.matchAll({ includeUncontrolled: true, type: 'window' });
  for (const c of clients) c.postMessage(msg);
}

/** SHA-256 of a response body, first 16 hex chars (matches tools/precache.mjs). */
async function digest(res) {
  const buf = await crypto.subtle.digest('SHA-256', await res.clone().arrayBuffer());
  return [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, '0')).join('').slice(0, 16);
}

/**
 * Download one precache file and check it against the manifest hash. Right after a deploy, a CDN edge
 * can still serve the previous copy of a file; caching that would pin a stale file (e.g. an icon
 * sprite without a new icon) to the new version. On a mismatch, retry with a cache-busting query
 * (a different URL the CDN hasn't cached), a few times with a short wait. Still wrong → the install
 * fails and the browser tries the update again later, while the current version keeps working.
 */
async function fetchVerified(url) {
  const want = hashes[url];
  for (let attempt = 0; attempt < 4; attempt++) {
    const target = attempt ? `${url}${url.includes('?') ? '&' : '?'}v=${want}-${attempt}` : url;
    const res = await fetch(new Request(target, { cache: 'reload' }));
    if (!res.ok) throw new Error(`precache ${url}: ${res.status}`);
    if (!want || (await digest(res)) === want) return res;
    await new Promise((r) => setTimeout(r, 1000 * attempt));
  }
  throw new Error(`precache ${url}: content doesn't match this version yet (CDN still updating)`);
}

/**
 * The copy of `url` in an older version's cache, if its content hash still matches this version.
 * The body is re-hashed (not trusted by name), so a reused file is exactly what a download would be.
 */
async function reusable(url, oldCaches) {
  const want = hashes[url];
  if (!want) return null;
  for (const old of oldCaches) {
    const hit = await old.match(url);
    if (hit && (await digest(hit)) === want) return hit;
  }
  return null;
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Every cached version, this one included (a re-install after a sw.js-only change reuses all of
    // it). Hashes decide what is reused, so a stale or partial cache is harmless.
    const oldCaches = await Promise.all((await caches.keys())
      .filter((k) => k.startsWith(PREFIX)).map((k) => caches.open(k)));
    const queue = [...files];
    let done = 0;
    let downloaded = 0;
    const total = queue.length;
    await broadcast({ type: 'precache-progress', done, total, downloaded, version });
    const worker = async () => {
      while (queue.length) {
        const url = queue.shift();
        let res = await reusable(url, oldCaches);
        if (!res) { res = await fetchVerified(url); downloaded += 1; }
        await cache.put(url, res);
        done += 1;
        if (done % 4 === 0 || done === total) broadcast({ type: 'precache-progress', done, total, downloaded, version });
      }
    };
    await Promise.all(Array.from({ length: CONCURRENCY }, worker));
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k.startsWith(PREFIX) && k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // network only, never cached
  const scope = new URL(self.registration.scope);
  if (!url.pathname.startsWith(scope.pathname)) return;

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    if (req.mode === 'navigate') {
      return (await cache.match('./')) || (await cache.match('index.html')) || fetch(req);
    }
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try {
      return await fetch(req);
    } catch {
      return new Response('Offline and not cached', { status: 504, headers: { 'Content-Type': 'text/plain' } });
    }
  })());
});
